name: Atualizar HTML Diário

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  atualizar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
        with:
          ref: main  # Garante que está usando a branch main

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script Python
        run: python flashscore.py

      - name: Subir alterações no HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Atualiza HTML automaticamente [skip ci]" || echo "Sem mudanças"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/tlvzz/campeonato-brasileiro.git HEAD:main
